// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbNtl9DmdUk_wu_r7Bbm7aTpizMcajeoo',
    appId: '1:727870723515:web:2c5a0b0b6eaaa1da1de09e',
    messagingSenderId: '727870723515',
    projectId: 'digital-twinmust',
    authDomain: 'digital-twinmust.firebaseapp.com',
    storageBucket: 'digital-twinmust.firebasestorage.app',
    measurementId: 'G-89E0DKNYFK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOVGvMrwiEuGbzCRqd35mgm_rNbCnOtWQ',
    appId: '1:727870723515:android:8fd9d687a7e916e91de09e',
    messagingSenderId: '727870723515',
    projectId: 'digital-twinmust',
    storageBucket: 'digital-twinmust.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCM-PpCNKH39HpMpIJeVdI2vdFAxoIW1tw',
    appId: '1:727870723515:ios:221b29c0a9a2d32f1de09e',
    messagingSenderId: '727870723515',
    projectId: 'digital-twinmust',
    storageBucket: 'digital-twinmust.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCM-PpCNKH39HpMpIJeVdI2vdFAxoIW1tw',
    appId: '1:727870723515:ios:221b29c0a9a2d32f1de09e',
    messagingSenderId: '727870723515',
    projectId: 'digital-twinmust',
    storageBucket: 'digital-twinmust.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbNtl9DmdUk_wu_r7Bbm7aTpizMcajeoo',
    appId: '1:727870723515:web:5e1eac75c4ea6aa21de09e',
    messagingSenderId: '727870723515',
    projectId: 'digital-twinmust',
    authDomain: 'digital-twinmust.firebaseapp.com',
    storageBucket: 'digital-twinmust.firebasestorage.app',
    measurementId: 'G-FE8Z04SJ7L',
  );
}
